i18next.addResourceBundle('en', 'translation', {
    "nav_home": "Home",
    "nav_how_to_use": "How to Use",
    "nav_faq": "FAQ",
    "nav_tos": "TOS",
    "nav_privacy": "Privacy",
    "nav_api": "API",
    "tagline": "High Quality Media X",
    "please_enter_url": "Please enter a URL to analyze.",
    "analysis_failed": "Analysis failed: {{error}}",
    "please_analyze_first": "Please analyze a URL first.",
    "failed_to_start_download": "Failed to start download.",
    "error_prefix": "Error: {{error}}",
    "connection_lost_retrying": "Connection lost, retrying...",
    "could_not_complete_task": "Could not complete task.",
    "could_not_retrieve_status": "Could not retrieve status.",
    "analyzing": "Analyzing...",
    "analyze": "Analyze",
    "mediaTitleDefault": "Unknown Title",
    "duration": "Duration",
    "originalQuality": "Original Quality",
    "originalFps": "Original FPS",
    "originalAudioQuality": "Original Audio Quality",
    "sizeEstimateDefault": "Estimated size: --",
    "refreshAndTryAgain": "Refresh browser and try again."
});

i18next.addResourceBundle('ko', 'translation', {
    "nav_home": "홈",
    "nav_how_to_use": "사용법",
    "nav_faq": "자주 묻는 질문",
    "nav_tos": "서비스 약관",
    "nav_privacy": "개인정보처리방침",
    "nav_api": "API",
    "tagline": "최고 품질 미디어 X",
    "please_enter_url": "분석할 URL을 입력해주세요.",
    "analysis_failed": "분석 실패: {{error}}",
    "please_analyze_first": "먼저 URL을 분석해주세요.",
    "failed_to_start_download": "다운로드 시작에 실패했습니다.",
    "error_prefix": "오류: {{error}}",
    "connection_lost_retrying": "연결 끊김, 재시도 중...",
    "could_not_complete_task": "작업을 완료할 수 없었습니다.",
    "could_not_retrieve_status": "상태를 가져올 수 없었습니다.",
    "analyzing": "분석 중...",
    "analyze": "분석",
    "mediaTitleDefault": "알 수 없는 제목",
    "duration": "재생 시간",
    "originalQuality": "원본 화질",
    "originalFps": "원본 FPS",
    "originalAudioQuality": "원본 음질",
    "sizeEstimateDefault": "예상 크기: --",
    "refreshAndTryAgain": "브라우저를 새로고침하고 다시 시도해주세요."
});